FROM rust:1.70

RUN apt-get update && \
    apt-get install -y libssl-dev pkg-config libmysqlclient-dev build-essential && \
    rm -rf /var/lib/apt/lists/*

RUN cargo install cargo-watch --version 8.0.0

WORKDIR /usr/src/app

# Source will be mounted by docker-compose for live edits.
EXPOSE 3001
CMD ["cargo", "watch", "-x", "run"]
